//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SalesAvenue.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SalesAvenueEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SalesAvenueEntities object using the connection string found in the 'SalesAvenueEntities' section of the application configuration file.
        /// </summary>
        public SalesAvenueEntities() : base("name=SalesAvenueEntities", "SalesAvenueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SalesAvenueEntities object.
        /// </summary>
        public SalesAvenueEntities(string connectionString) : base(connectionString, "SalesAvenueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SalesAvenueEntities object.
        /// </summary>
        public SalesAvenueEntities(EntityConnection connection) : base(connection, "SalesAvenueEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tokenId">No Metadata Documentation available.</param>
        public ObjectResult<UserRegisterationType> UserRegisterationGet(Nullable<global::System.Guid> tokenId)
        {
            ObjectParameter tokenIdParameter;
            if (tokenId.HasValue)
            {
                tokenIdParameter = new ObjectParameter("TokenId", tokenId);
            }
            else
            {
                tokenIdParameter = new ObjectParameter("TokenId", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<UserRegisterationType>("UserRegisterationGet", tokenIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="store_name">No Metadata Documentation available.</param>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        /// <param name="user_status_id">No Metadata Documentation available.</param>
        /// <param name="token_id">No Metadata Documentation available.</param>
        public int RegisterUsers(global::System.String store_name, global::System.String email, global::System.Byte[] password, Nullable<global::System.Int16> user_status_id, Nullable<global::System.Guid> token_id)
        {
            ObjectParameter store_nameParameter;
            if (store_name != null)
            {
                store_nameParameter = new ObjectParameter("store_name", store_name);
            }
            else
            {
                store_nameParameter = new ObjectParameter("store_name", typeof(global::System.String));
            }
    
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("email", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("password", typeof(global::System.Byte[]));
            }
    
            ObjectParameter user_status_idParameter;
            if (user_status_id.HasValue)
            {
                user_status_idParameter = new ObjectParameter("user_status_id", user_status_id);
            }
            else
            {
                user_status_idParameter = new ObjectParameter("user_status_id", typeof(global::System.Int16));
            }
    
            ObjectParameter token_idParameter;
            if (token_id.HasValue)
            {
                token_idParameter = new ObjectParameter("token_id", token_id);
            }
            else
            {
                token_idParameter = new ObjectParameter("token_id", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction("RegisterUsers", store_nameParameter, emailParameter, passwordParameter, user_status_idParameter, token_idParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SalesAvenueModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="storeName">Initial value of the StoreName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="tokenID">Initial value of the TokenID property.</param>
        public static User CreateUser(global::System.Int32 userID, global::System.String storeName, global::System.String email, global::System.Guid tokenID)
        {
            User user = new User();
            user.UserID = userID;
            user.StoreName = storeName;
            user.Email = email;
            user.TokenID = tokenID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] UserPassword
        {
            get
            {
                return StructuralObject.GetValidValue(_UserPassword);
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.Byte[] _UserPassword;
        partial void OnUserPasswordChanging(global::System.Byte[] value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UserStatusID
        {
            get
            {
                return _UserStatusID;
            }
            set
            {
                OnUserStatusIDChanging(value);
                ReportPropertyChanging("UserStatusID");
                _UserStatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserStatusID");
                OnUserStatusIDChanged();
            }
        }
        private Nullable<global::System.Int16> _UserStatusID;
        partial void OnUserStatusIDChanging(Nullable<global::System.Int16> value);
        partial void OnUserStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TokenID
        {
            get
            {
                return _TokenID;
            }
            set
            {
                OnTokenIDChanging(value);
                ReportPropertyChanging("TokenID");
                _TokenID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TokenID");
                OnTokenIDChanged();
            }
        }
        private global::System.Guid _TokenID;
        partial void OnTokenIDChanging(global::System.Guid value);
        partial void OnTokenIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SalesAvenueModel", Name="UserRegisterationType")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class UserRegisterationType : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRegisterationType object.
        /// </summary>
        /// <param name="storeName">Initial value of the StoreName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static UserRegisterationType CreateUserRegisterationType(global::System.String storeName, global::System.String email)
        {
            UserRegisterationType userRegisterationType = new UserRegisterationType();
            userRegisterationType.StoreName = storeName;
            userRegisterationType.Email = email;
            return userRegisterationType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    }

    #endregion
    
}
